title: 我的项目
subtitle: 这里展示了我的一些个人项目和开源贡献

# 指定使用的模板文件名，现有页面模板可见templates\pages
template: projects

categories:
  - name: 个人项目
    icon: fas fa-code
    sites:
      - name: 个人网站
        icon: fa-solid fa-user
        description: 一个简洁美观的个人网站
        url: "https://bento.me/yufengxiang"
      - name: MoonTV
        icon: fa-brands fa-youtube
        description: 基于cloudflare部署的影视资源网
        url: "https://itv.mvpbook.cn"
      - name: 个人博客
        icon: fas fa-blog
        description: 使用Hexo搭建的技术博客
        url: "#"
  - name: 开源贡献
    icon: fas fa-code-branch
    sites:
      - name: Project A
        icon: fab fa-github
        description: 开源项目贡献
        url: "#"
      - name: Project B
        icon: fab fa-github
        description: 开源项目贡献
        url: "#" 
