- name: 首页
  icon: fas fa-home
  id: home
  active: true
- name: 项目
  icon: fa-regular fa-face-smile
  id: projects
- name: 朋友
  icon: fas fa-users
  id: friends
- name: 书签
  icon: fas fa-bookmark
  id: bookmarks 
